baseURL = "https://celestialminds.netlify.app/"
languageCode = "en-us"
title = "Celestial Mind"
theme = "hugo-digital-garden-theme"
themesdir = "./themes"
copyright = "Garuda"


[params]
  name = "The Grid"
  description = "A celestial Mind."
  initials = "CM"
  googleAnalytics = ""

  [[params.social]]
    name = "Twitter"
    link = "https://twitter.com/home"
    icon = "fab fa-twitter"

  [[params.social]]
    name = "Github"
    link = "https://github.com/stardoom4"
    icon = "fab fa-github"

  [[params.social]]
    name = "Medium" 
    link = "https://medium.com"
    icon = "fab fa-medium-m"

  [[params.social]]
    name = "LinkedIn"
    link = "https://linkedin.com"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "Digital Garden"
    url = "/garden/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Library"
    url = "/library/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4


[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'
